### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by clbarnes** [pkolaczk/fclones#33] opened 2021-01-15 12:20 UTC
It would be nice to `cargo install fclones`, have cargo track versions, and so on. This could be part of the CI pipeline, and/or there's `cargo-release` which handles tagging and so on.

**Comment by clbarnes** [comment] 2021-01-15 13:25
Presumably this is blocked by some system dependencies (like pcre2). These are currently preventing me from compiling this.

**Comment by pkolaczk** [comment] 2021-02-21 13:46
Can you paste the error you are getting?
I just updated a few things, so it should be ok now - CircleCI is happy.

**Comment by pkolaczk** [comment] 2021-02-21 13:55
Ah, ok, I get it:

```
cargo publish --dry-run
error: all dependencies must have a version specified when publishing.
dependency `pcre2` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
```

The problem is that the pcre2-sys crate hasn't merged my PR about partial matching yet, so I can't use the upstream version. 
Any ideas what to do in this case?

**Comment by clbarnes** [comment] 2021-02-22 00:03
You can't publish a crate with unpublished dependencies, so if you were really absolutely fixed on using pcre you could publish your own pcre-sys fork crate and depend on that.

What does pcre-sys give you which the standard rust regex crate doesn't, and is it worth the headache of external dependencies when the regex crate is fast, popular, good feature selection etc?

**Comment by pkolaczk** [comment] 2021-02-22 07:01
I need partial maching to be able to tell if an initial part of the path can potentially match a pattern. Does any of the Rust-native creates support it?

**Comment by clbarnes** [comment] 2021-02-22 10:26
Ah, got it. It doesn't look like the major `regex` does, nor anything in its ecosystem, so it may be necessary to stick with pcre. Looking forward to seeing this out there though, it looked like the best option when I was doing a 500TB dupe search but I just couldn't get it to build on my server (I went with fddf in the end).

**Comment by pkolaczk** [comment] 2021-02-22 15:22
Can you share what the problem was with building it? Publishing is one thing, but building should work now - it fetches pcre2-sys from my fork. If pcre dependency is a problem on some systems, maybe I could feature-flag it. This would make searching a bit slower in some cases, but that may be less of an issue than not being able to compile it at all.

**Comment by pkolaczk** [comment] 2021-04-10 20:06
Done!
https://crates.io/crates/fclones

**Closed by pkolaczk** 2021-04-10 20:06 UTC
Labels: build
